apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: topo-demo
  labels:
    app: whoami
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: whoami
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - containerPort: 80
