apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: prod-nginx
  labels:
    name: nginx
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
