apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: resource-demo
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress","--cpu","2"]
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "64Mi"
