apiVersion: v1
kind: Pod
metadata:
  name: mem-demo
  namespace: resource-demo
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress","--vm","1","--vm-bytes","200M","--vm-hang","1"]
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "200m"
        memory: "100Mi"
